version: '4'
services:
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres_order_service
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
